version: '3.6'

services:
    node:
        image: node:18
        container_name: binge-node
        build:
          context: .
          dockerfile: Dockerfile
        restart: always
        ports:
            - 3000:3000
