version: '3.6'

services:

  mongo:
    image: mongo:latest
    container_name: binge-mongo
    restart: always
    ports:
      - 5151:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: bingedb
    volumes:
      - ./binge-mongo:/data/db