name: Deploy to Google Cloud
'on':
    push:
        branches:
            - master
jobs:
    setup-build-publish-deploy:
        name: Setup, Build, Publish, and Deploy
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        # Setup gcloud CLI
        - uses: GoogleCloudPlatform/github-actions/setup-gcloud@v2
          with:
              service_account_email: ${{ secrets.GCP_EMAIL }}
              service_account_key: ${{ secrets.GCP_CREDENTIALS }}
              export_default_credentials: true

        # Configure Docker with Credentials
        - name: Configure Docker
          run: |
              gcloud auth configure-docker

        # Build the Docker image
        - name: Build & Publish
          run: |
              gcloud config set project ${{ secrets.GCP_PROJECT }}
              gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}
              gcloud config set run/region asia-south1
