name: Deploy to Google Cloud
'on':
    push:
        branches:
            - master
jobs:
    setup-build-publish-deploy:
        name: Setup, Build, Publish, and Deploy
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        # Setup gcloud CLI
        - id: 'auth'
          uses: 'google-github-actions/auth@v1'
          with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v1'

        # Configure Docker with Credentials
        - name: Configure Docker
          run: |
              gcloud auth configure-docker

        # Build the Docker image
        - name: Build & Publish
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: gcr.io/binge-on/cloudrun/binge-node:latest

        # Deploy the Docker image to the GKE cluster
        - name: Deploy to GCR
          uses: 'google-github-actions/deploy-cloudrun@v1'
          with:
            image: gcr.io/binge-on/cloudrun/binge-node:latest
            service: 'binge-node'
            region: 'asia-east1'
            env_vars: |
              CONNECTION_STRING=${{ vars.CONNECTION_STRING }}
              

